[behave]
paths = features
stdout_capture = false
stderr_capture = false
log_capture = false
junit = true
junit_directory = reports/junit
# Requires: pip install allure-behave==2.16.0
format = allure_behave.formatter:AllureFormatter
outfiles = reports/allure
